# Generated by Django 5.0.2 on 2024-04-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbeautystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
