# Generated by Django 5.0.2 on 2024-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbeautystore', '0002_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration_field',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
