# Generated by Django 5.0.2 on 2024-04-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbeautystore', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
